name: Compile Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Compile
    runs-on: ubuntu-latest

    steps:
      # Step 2: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 3: Set up CMake
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "3.26"

      # Step 2: Cache APT packages
      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: g++ make libboost-all-dev pybind11-dev
          version: 1.0

      # Step 5: Configure the project with CMake
      - name: Configure with CMake
        run: |
          mkdir build
          cd build
          cmake ..

      # Step 6: Build the project
      - name: Build the project
        run: |
          cd build
          cmake --build .
